sudo: required

services:
  - docker

before_install:
  - docker build -t thiagofigueiro/flume:ci .
  - sudo service docker restart ; sleep 10
  - docker run -d -p 127.0.0.1:44444:44444 thiagofigueiro/flume:ci

script:
  - echo "Hello world" | nc -q 1 localhost 44444

after_script:
  - docker rm -f $(docker ps -a -q)
